create table public.iskonto_alisveris (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  musteri bigint not null,
  alis_tip text not null,
  alis_litre double precision not null,
  alis_tutar double precision not null,
  iskonto_oran double precision not null,
  net_tutar double precision not null,
  litre_fiyat double precision not null,
  personel uuid not null,
  aciklama text null,
  fatura_foto text null,
  constraint iskonto_alisveris_pkey primary key (id),
  constraint iskonto_alisveris_musteri_fkey foreign KEY (musteri) references iskonto_listesi (id),
  constraint iskonto_alisveris_personel_fkey foreign KEY (personel) references auth.users (id)
) TABLESPACE pg_default;

create table public.iskonto_listesi (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  plaka text not null,
  oran double precision not null,
  aciklama text null,
  aktif boolean not null default true,
  constraint iskonto_listesi_pkey primary key (id)
) TABLESPACE pg_default;

create table public.user_details (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  uid uuid not null,
  name text not null,
  role text not null,
  tel text null,
  constraint user_details_pkey primary key (id),
  constraint user_details_uid_fkey foreign KEY (uid) references auth.users (id)
) TABLESPACE pg_default;